spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apitable?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: asdf1234
  liquibase:
    # 指定配置文件路径
    change-log: classpath:db/db.changelog-master.xml
    # 覆盖本地 ddl dml
    drop-first: true
    # 是否启用
    enabled: true
    # 记录版本日志表
    database-change-log-table: databasechangelog
    # 记录版本改变lock表
    database-change-log-lock-table: databasechangeloglock